- name: Azure CLI | Pre-Reqs
  hosts: localhost
  become: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    rhsm_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.10-rpms
      - rhel-7-fast-datapath-rpms
      - rhel-7-server-ansible-2.5-rpms
    rhsm_repos_disable:
      - rhel-7-server-htb-rpms
      - rhel-7-server-ose-3.9-rpms
    message: |
      This host is now setup, next steps are
        Copy vars.yml.example to vars.yml
        - cp vars.yml.example vars.yml
        Edit vars.yml
        - vi vars.yml

  tasks:
    - name: Setup | Disable RHSM repositories 
      rhsm_repository: 
        name: "{{ rhsm_repos_disable }}" 
        state: disabled

    - name: Setup | Enable RHSM repositories 
      rhsm_repository: 
        name: "{{ rhsm_repos }}" 
        state: enabled 

    - name: Setup | Install required packages 
      yum: 
        name: "{{ item }}" 
        state: latest 
      loop: 
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
        - python2-pip 
        - atomic-openshift-clients
        - openshift-ansible
        - python-devel
        - jq

    - name: Setup | Remove epel
      yum:
        name: epel-release
        state: absent

    - name: Setup | Install Azure ansible pip modules
      pip:
        name: "{{ item }}"
      loop:
        - boto3
        - boto
        - awscli

    - name: 'Create the AWS config directory'
      file:
        path: "{{ home_dir }}/.aws"
        state: directory
        mode: 0755
 
    - name: 'Copy AWS CLI config'
      template:
        src: aws_cli_config.j2
        dest: "{{ home_dir }}/.aws/config"
        mode: 0600
 
    - name: 'Copy AWS CLI credentials'
      tags: 'aws-cli'
      template:
        src: aws_cli_credentials.j2
        dest: "{{ home_dir }}/.aws/credentials"
        mode: 0600
 
     - name: Setup | Prompt
       debug:
         msg: "{{ message.split('\n') }}"
 
