---
- name: Azure CLI | Pre-Reqs
  hosts: localhost
  become: True
  vars_files:
    - ./vars.yml
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    rhsm_repos:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ose-3.11-rpms
        - rhel-7-server-ansible-2.6-rpms
        - rhel-7-server-rh-common-rpms
    rhsm_pool: '8a85f98c60c2c2b40160c32445b41b29' 
    rhsm_repos_disable:
      - rhel-7-server-htb-rpms
      - rhel-7-server-ose-3.9-rpms
      - rhel-7-server-ose-3.10-rpms
      - rhel-7-server-ansible-2.6-rpms
    setup_complete_message: |
      This host is now setup, next steps are
        Copy vars.yml.example to vars.yml
        - cp vars.yml.example vars.yml
        Edit vars.yml
        - vi vars.yml
        Configure AWS CLI Credentials
        - aws configure
        or with a profile
        - aws configure --profile profilename
    fail_msg: |
        AWS_ACCESS_KEY_ID and/or
        AWS_SECRET_ACCESS_KEY not found,
        make sure the following variables are correct in vars.yml
          - aws_access_key
          - aws_secret_key
  pre_tasks:
    - name: Pre-Setup | AWS_ACCESS_KEY Check"
      debug:
        msg: "{{ fail_msg.split('\n') }}"
      when: ( aws_access_key is not defined or aws_access_key == '') or
            (aws_secret_key is not defined or aws_secret_key == '')
      failed_when: (aws_access_key is not defined or aws_access_key == '') or
            (aws_secret_key is not defined or aws_secret_key == '')

  tasks:
    - name: Setup | Disable RHSM repositories
      rhsm_repository:
        name: "{{ rhsm_repos_disable }}"
        state: disabled

    - name: Setup | Enable RHSM repositories
      rhsm_repository:
        name: "{{ rhsm_repos }}"
        state: enabled

    - name: Setup | Install required packages
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - python2-pip
        - atomic-openshift-clients
        - openshift-ansible
        - python-devel
        - jq

    - name: Setup | Remove epel
      yum:
        name: epel-release
        state: absent

    - name: Setup | Install AWS ansible pip modules
      pip:
        name: "{{ item }}"
      loop:
        - boto3
        - boto
        - awscli

    #- name: Setup | Create the AWS config directory
    #  file:
    #    path: "{{ home_dir }}/.aws"
    #    state: directory
    #    mode: 0755

    #- name: Setup | Check for AWS CLI config files
    #  stat:
    #    path: "{{ home_dir }}/.aws/config"
    #  register: aws_config_file

    #- name: Setup | Check for AWS CLI credentials files
    #  stat:
    #    path: "{{ home_dir }}/.aws/credentials"
    #  register: aws_config_file

    #- name: Setup | Copy AWS CLI config
    #  template:
    #    src: aws_cli_config.j2
    #    dest: "{{ home_dir }}/.aws/config"
    #    mode: 0600

    #- name: 'Copy AWS CLI credentials'
    #  tags: 'aws-cli'
    #  template:
    #    src: aws_cli_credentials.j2
    #    dest: "{{ home_dir }}/.aws/credentials"
    #    mode: 0600

    - name: Setup | Prompt
      debug:
        msg: "{{ setup_complete_message.split('\n') }}"

