---
- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} S3 bucket ( hosted registry )"
  s3_bucket:
    name: "{{ clusterid }}.{{ dns_domain }}-registry"
    region: "{{ aws_region }}"
    state: "{{ state | default('present') }}"
    tags:
      clusterid: "{{ clusterid }}"
  retries: 3
  delay: 3
